spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 100
      minimum-idle: 5
  application:
    name: link-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
server:
  port: 8070
